config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'weddings#index'

  resources :weddings do
    resources :guests
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :weddings
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wedding.rb
class Wedding < ApplicationRecord

  has_many :guests

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
def index
  @wedding = Wedding.find(params[:wedding_id])
  @guests = @wedding.guests
end

def show
  @guest = Guest.find(params[:wedding_id, :id])
end

def new
  @wedding = Wedding.find(params[:wedding_id])
  @guest = @wedding.guests.new
end

def create
  guest_params
  @wedding = Wedding.find(params[:wedding_id])
  @guest = @wedding.guests.new(guest_params)


  if @guest.save
     redirect_to @guest
  else
     render 'new'
  end
end

def edit
  @guest = Guest.find(params[:id])
end

def update
  @guest = Guest.find(params[:id])

  guest_params

  if @guest.update_attributes(guest_params)
    redirect_to @guest
  else
    render 'edit'
  end
end

def destroy
  @guest = Guest.find(params[:id])

  @guest.destroy

  redirect_to guests_path
end

private

def guest_params
  params.require(:guest).permit(:name, :adults, :children, :food_preference, :attending, :wedding_id)
end

end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
def index
  @weddings = Wedding.all
end

def show
  @wedding = Wedding.find(params[:id])
end

def new
  @wedding = Wedding.new
end

def create
  wedding_params

  @wedding = Wedding.new(wedding_params)

  if @wedding.save
     redirect_to @wedding
  else
     render 'new'
  end
end

def edit
  @wedding = Wedding.find(params[:id])
end

def update
  @wedding = Wedding.find(params[:id])

  wedding_params

  if @wedding.update_attributes(wedding_params)
    redirect_to @wedding
  else
    render 'edit'
  end
end

def destroy
  @wedding = Wedding.find(params[:id])

  @wedding.destroy

  redirect_to weddings_path
end

private

def wedding_params
  params.require(:wedding).permit(:name, :date, :location)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/guests/_form.html.erb
<%= form_for [@wedding, @wedding.guests.new] do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :adults %>
  <%= f.text_field :adults %>

  <%= f.label :children %>
  <%= f.text_field :children %>

  <%= f.label :food_preference %>
  <%= f.text_field :food_preference %>

  <%= f.check_box :attending %>
  <%= label_tag(:attending, "I'm attending the wedding") %>

  <%= f.submit (@guest.new_record? ? "Create" : "Update") %>

<% end %>

app/views/guests/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RSVP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/weddings/index.html.erb
<% @weddings.each do |wedding| %>
<p><%= link_to wedding.name, new_wedding_guest_path(wedding.id) %></p>
<% end %>